-- =============================================================================
-- DEPRECATED — do not rely on this for free-tier keep-alive
-- =============================================================================
--
-- Prefer the GitHub Action instead:
--   .github/workflows/keep-supabase-alive.yml
--
-- Why this failed in practice:
--   1. net._http_response stayed empty — pg_net never completed usable API hits
--   2. Free pausing needs external "user" API activity (a few requests/day)
--   3. Once the project pauses, pg_cron inside the DB stops with it
--
-- Remove the old job if it is still scheduled:
--   SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'keep-project-active';
--
-- =============================================================================
